#!/usr/bin/env bash
# Generate .stow-local-ignore based on current OS
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOTFILES_DIR="$(dirname "$SCRIPT_DIR")"
OUTPUT_FILE="$DOTFILES_DIR/.stow-local-ignore"

COMMON_FILE="$SCRIPT_DIR/ignore.common"
MACOS_FILE="$SCRIPT_DIR/ignore.macos"
LINUX_FILE="$SCRIPT_DIR/ignore.linux"

# Detect OS
OS="$(uname -s)"

# Determine which OS-specific file to use
case "$OS" in
Darwin)
    OS_FILE="$MACOS_FILE"
    OS_NAME="macOS"
    ;;
Linux)
    OS_FILE="$LINUX_FILE"
    OS_NAME="Linux"
    ;;
*)
    echo "Error: Unsupported OS: $OS" >&2
    exit 1
    ;;
esac

# Generate header
cat >"$OUTPUT_FILE" <<EOF
# This file is AUTO-GENERATED by .stow/generate-ignore.sh
# DO NOT EDIT MANUALLY - Changes will be overwritten
# Generated for: $OS_NAME ($OS)
# Generated at: $(date -u +"%Y-%m-%d %H:%M:%S UTC")

EOF

# Append common patterns
if [[ -f "$COMMON_FILE" ]]; then
    echo "# Common patterns (all platforms)" >>"$OUTPUT_FILE"
    cat "$COMMON_FILE" >>"$OUTPUT_FILE"
    echo "" >>"$OUTPUT_FILE"
else
    echo "Warning: $COMMON_FILE not found" >&2
fi

# Append OS-specific patterns
if [[ -f "$OS_FILE" ]]; then
    echo "# OS-specific patterns for $OS_NAME" >>"$OUTPUT_FILE"
    cat "$OS_FILE" >>"$OUTPUT_FILE"
    echo "" >>"$OUTPUT_FILE"
else
    echo "Warning: $OS_FILE not found" >&2
fi

echo "Generated $OUTPUT_FILE for $OS_NAME"
echo "You can now run: stow -t ~ ."
